server:
  port: 8083

spring:
  application:
    name: gateway

  # spring cloud gateway 설정
  cloud:    gateway:      routes:      - id: apple_rest        uri: http://localhost:8081        predicates:
        - Path=/apple/rest/
        - After=2019-09-23T15:30:00.000+09:00[Asia/Seoul]

      - id: apple_banana_rest
        uri: http://localhost:8081
        predicates:
        - Path=/apple/{sabun}/{name}/{division}/ 

  management:
    endpoints:
      web:
        exposure:
          include: "*"